server:
   port: 8003

mybatis:
   config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
   type-aliases-package: dawn.cloud.api.entity    # 所有Entity别名类所在包
   mapper-locations:
   - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: dawncloud-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB03              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
#eureka注册
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: dawncloud-dept-8003
    prefer-ip-address: true
info: #配置项目信息在eureka页面上面,当鼠标点击到服务器名称级IP时,左下角会有响应提示
  app.name: hhf-microservicecloud
  company.name: https://www.jianshu.com/u/c7adbc6b595c  #我的博客地址
  build.artifactId: $project.artifactId$
  build.version: $project.version$